name: run-test
on: [push, pull_request]

env:
  GO111MODULE: on
jobs:
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cmd/krane
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test krane
        run: cd ../../ && go test -v ./...
