name: run-test
on: [push, pull_request]

env:
  GO111MODULE: on
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...:
     
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cmd/krane
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test krane
        run: cd ../../ && go test -v ./...
